# Generated by Django 4.2.10 on 2024-06-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_default_email_profile_default_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
