# Generated by Django 4.2.10 on 2024-06-02 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=5)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.department')),
            ],
        ),
    ]
