# Generated by Django 4.2.10 on 2024-06-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='list_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
