# Generated by Django 4.2.10 on 2024-06-14 16:20

from django.db import migrations, models
import products.validators


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='list_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[products.validators.validate_non_negative]),
        ),
    ]
