# Generated by Django 4.2.10 on 2024-06-14 16:23

from django.db import migrations, models
import products.validators


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_list_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[products.validators.validate_non_negative]),
        ),
    ]
